
package Vista;

import Base.GUI;
import Base.Reporte;
import ConexionDB.Conexion;
import Control.AlarmasEmitidasCTR;
import Control.MantenimientoEquipamientoCTR;
import Reportes.Informes;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


public class HistorialMantenimientos extends javax.swing.JDialog {
    private MantenimientoEquipamientoCTR ctr;
    
    public HistorialMantenimientos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/icon.png")).getImage());
        initComponents();
        formatoTabla();
        GUI.setFormatoFecha(fechaDesde);
        GUI.setFormatoFecha(fechaHasta);
        jPanel1.setVisible(true);
        setLocationRelativeTo(null);
        ctr = new MantenimientoEquipamientoCTR(this);
    }
    public HistorialMantenimientos(){
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/icon.png")).getImage());
        initComponents();
        formatoTabla();
        GUI.setFormatoFecha(fechaDesde);
        GUI.setFormatoFecha(fechaHasta);
        jPanel1.setVisible(true);
        setLocationRelativeTo(null);
        ctr = new MantenimientoEquipamientoCTR(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        fechaDesde = new javax.swing.JFormattedTextField();
        fechaHasta = new javax.swing.JFormattedTextField();
        cboPdf = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Historicos de Mantenimientos");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingreso de Fecha - Horario "));
        jPanel1.setLayout(null);

        jLabel2.setText("Desde");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 30, 14);

        jLabel3.setText("Hasta");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(230, 30, 28, 14);

        btnVisualizar.setText("Filtrar Datos");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVisualizar);
        btnVisualizar.setBounds(540, 50, 120, 40);

        try {
            fechaDesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fechaDesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaDesdeActionPerformed(evt);
            }
        });
        jPanel1.add(fechaDesde);
        fechaDesde.setBounds(20, 50, 170, 40);
        jPanel1.add(fechaHasta);
        fechaHasta.setBounds(230, 50, 160, 40);

        cboPdf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "GENERAL", "FILTRADO" }));
        cboPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPdfActionPerformed(evt);
            }
        });
        jPanel1.add(cboPdf);
        cboPdf.setBounds(780, 50, 90, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        //ctr.cargarAlarmas();
        ctr.cargarMantenimientos(fechaDesde.getText(), fechaHasta.getText());
    }//GEN-LAST:event_btnVisualizarActionPerformed

    private void fechaDesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaDesdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaDesdeActionPerformed

    private void cboPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPdfActionPerformed
        // TODO add your handling code here:
        String tipo_usuario = cboPdf.getSelectedItem().toString();
        if(tipo_usuario.equals("GENERAL")){
            try {
            Conexion con = new Conexion();
            Connection conn = con.obtenerConexion();
            
            JasperReport reporte = null;
          
            String path = "src/Reportes/report7.jasper";
          
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte,null, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
            
        } catch (JRException ex) {
            Logger.getLogger(HistorialMantenimientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(tipo_usuario.equals("FILTRADO")){
            try {
            Conexion con = new Conexion();
            Connection conn = con.obtenerConexion();
            
            JasperReport reporte = null;
          
            String path = "src/Reportes/report8.jasper";
            
           
            
            
            Map parametro = new HashMap();
            parametro.put("desde", fechaDesde.getText().toString());
            parametro.put("hasta", fechaHasta.getText().toString());
            
            
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            
            JasperPrint jprint = JasperFillManager.fillReport(reporte,parametro, conn);
            
            JasperViewer view = new JasperViewer(jprint, false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            
            view.setVisible(true);
            
            
        } catch (JRException ex) {
            Logger.getLogger(HistorialMantenimientos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_cboPdfActionPerformed
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialMantenimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                HistorialMantenimientos dialog = new HistorialMantenimientos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<String> cboPdf;
    public javax.swing.JFormattedTextField fechaDesde;
    public javax.swing.JFormattedTextField fechaHasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

     private void formatoTabla() {
        String[] cabeceras = {"Id", "Tipo Mantenimiento", "Equipo", "Comentario", "Usuario","Nombres","Fecha"};

        DefaultTableModel m = new DefaultTableModel(cabeceras, 0) {
            @Override
            public Class<?> getColumnClass(int column) {
                if (getRowCount() > 0) {
                    Object value = getValueAt(0, column);
                    if (value != null) {
                        return getValueAt(0, column).getClass();
                    }
                }

                return super.getColumnClass(column);
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tabla.setModel(m);
        tabla.setCellSelectionEnabled(false);
        tabla.setRowSelectionAllowed(true);
        tabla.setFillsViewportHeight(true);

        tabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabla.getColumnModel().getColumn(0).setMaxWidth(50); //icon
        tabla.getColumnModel().getColumn(0).setPreferredWidth(50);

        tabla.getColumnModel().getColumn(1).setMaxWidth(200); //Tipo mantenimiento
        tabla.getColumnModel().getColumn(1).setPreferredWidth(200);

        tabla.getColumnModel().getColumn(2).setMaxWidth(140); //Equipo
        tabla.getColumnModel().getColumn(2).setPreferredWidth(140);
        
        tabla.getColumnModel().getColumn(3).setMaxWidth(230); //comentario
        tabla.getColumnModel().getColumn(3).setPreferredWidth(230);
        
        tabla.getColumnModel().getColumn(4).setMaxWidth(140); //Usuario
        tabla.getColumnModel().getColumn(4).setPreferredWidth(140);
        
        tabla.getColumnModel().getColumn(5).setMaxWidth(105); //Nombres
        tabla.getColumnModel().getColumn(5).setPreferredWidth(105);
        
        tabla.getColumnModel().getColumn(6).setMaxWidth(150); //Fechas
        tabla.getColumnModel().getColumn(6).setPreferredWidth(150);

        //"Id", "Descripción","Nro. Serie","Modelo","Comentario"
        GUI.alinerColumnaTabla(tabla, 0, GUI.ALINEACION.IZQUIERDA);
        GUI.alinerColumnaTabla(tabla, 1, GUI.ALINEACION.IZQUIERDA);
        GUI.alinerColumnaTabla(tabla, 2, GUI.ALINEACION.IZQUIERDA);
        jScrollPane1.setBorder(BorderFactory.createEmptyBorder());
        tabla.setIntercellSpacing(new Dimension(15, 0));
        //GUI.setFiltroTabla(tabla, txBuscar.getText(), FILTRO_COLS);
    }
    

}

