/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.dto.UsuarioDTO;
import java.awt.Dimension;
import javax.swing.ImageIcon;


/**
 *
 * @author guido ruiz
 */
public class home extends javax.swing.JFrame {

    UsuarioDTO mod;
    public static  String nombreUsuario;
    public static  String Usuario_home;
    public static  String correo;
    public static String celular;
    public static int id_usuario_home;
    
    public home() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/icon.png")).getImage());
        this.setMinimumSize(new Dimension(1200, 600));
        setLocationRelativeTo(null);
    }
    public home(UsuarioDTO mod){
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/Iconos/icon.png")).getImage());
        this.setMinimumSize(new Dimension(1200, 600));
        setLocationRelativeTo(null);
        this.mod = mod;
        
        Usuario_home = mod.getUsusario();
        nombreUsuario = mod.getNombre();
        correo = mod.getCorreo();
        celular = mod.getTelefono();
        id_usuario_home = mod.getId();
        lblNombre.setText(mod.getNombre());
        lblRol.setText(mod.getUsusario());
        
        if(mod.getUsusario().equals("Administrador") ){
            
        } else if (mod.getUsusario().equals("Operador") ){
          
            menuMantenimiento.setVisible(false);
            menuRegistro.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        lblNombre = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMantenimiento = new javax.swing.JMenu();
        subMantenimientoMarca = new javax.swing.JMenuItem();
        subMantenimientoProcedencia = new javax.swing.JMenuItem();
        Equipamiento = new javax.swing.JMenuItem();
        MantenimentoEquipamiento = new javax.swing.JMenuItem();
        MantenimientoEquipamiento = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        MonitoreoCentral = new javax.swing.JMenu();
        historialMantenimiento = new javax.swing.JMenu();
        Salir = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        lblNombre.setBackground(new java.awt.Color(0, 204, 204));
        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        lblRol.setBackground(new java.awt.Color(0, 204, 204));
        lblRol.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRol.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel4.setText("Sistema de control");

        lbInfo.setBackground(new java.awt.Color(255, 204, 51));
        lbInfo.setAlignmentY(0.0F);
        lbInfo.setOpaque(true);

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 51));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 153, 0)));

        menuMantenimiento.setText("Mantenimiento");

        subMantenimientoMarca.setText("Marca");
        subMantenimientoMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subMantenimientoMarcaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMantenimientoMarcaMousePressed(evt);
            }
        });
        menuMantenimiento.add(subMantenimientoMarca);

        subMantenimientoProcedencia.setText("Procedencia");
        subMantenimientoProcedencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subMantenimientoProcedenciaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                subMantenimientoProcedenciaMousePressed(evt);
            }
        });
        menuMantenimiento.add(subMantenimientoProcedencia);

        Equipamiento.setText("Equipamiento");
        Equipamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EquipamientoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EquipamientoMousePressed(evt);
            }
        });
        Equipamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EquipamientoActionPerformed(evt);
            }
        });
        menuMantenimiento.add(Equipamiento);

        MantenimentoEquipamiento.setText("Tipo Mantenimiento");
        MantenimentoEquipamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MantenimentoEquipamientoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MantenimentoEquipamientoMousePressed(evt);
            }
        });
        MantenimentoEquipamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimentoEquipamientoActionPerformed(evt);
            }
        });
        menuMantenimiento.add(MantenimentoEquipamiento);

        MantenimientoEquipamiento.setText("Mantenimiento Equipamiento");
        MantenimientoEquipamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MantenimientoEquipamientoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MantenimientoEquipamientoMousePressed(evt);
            }
        });
        menuMantenimiento.add(MantenimientoEquipamiento);

        jMenuBar1.add(menuMantenimiento);

        menuRegistro.setText("Registro");
        menuRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuRegistroMousePressed(evt);
            }
        });
        jMenuBar1.add(menuRegistro);

        MonitoreoCentral.setText("Monitoreo");
        MonitoreoCentral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MonitoreoCentralMousePressed(evt);
            }
        });
        jMenuBar1.add(MonitoreoCentral);

        historialMantenimiento.setText("Historial Mantenimientos");
        historialMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                historialMantenimientoMousePressed(evt);
            }
        });
        historialMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialMantenimientoActionPerformed(evt);
            }
        });
        jMenuBar1.add(historialMantenimiento);

        Salir.setText("Salir");
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalirMousePressed(evt);
            }
        });
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jMenuBar1.add(Salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(199, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
            .addComponent(lbInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(lblRol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subMantenimientoMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMantenimientoMarcaMouseClicked
                           //
                         // 
                          Marca marca = new Marca();
                          //
                          //
                          marca.setVisible(true);
    }//GEN-LAST:event_subMantenimientoMarcaMouseClicked

    private void subMantenimientoProcedenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMantenimientoProcedenciaMouseClicked
        Procedencia frmHome = new Procedencia();
        frmHome.setVisible(true);
    }//GEN-LAST:event_subMantenimientoProcedenciaMouseClicked

    private void MantenimentoEquipamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimentoEquipamientoMouseClicked
       TipoMantenimiento tipoM = new TipoMantenimiento();
       tipoM.setVisible(true);
    }//GEN-LAST:event_MantenimentoEquipamientoMouseClicked

    private void subMantenimientoMarcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMantenimientoMarcaMousePressed
          Marca marca = new Marca();
          marca.setVisible(true);
    }//GEN-LAST:event_subMantenimientoMarcaMousePressed

    private void subMantenimientoProcedenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subMantenimientoProcedenciaMousePressed
        Procedencia frmHome = new Procedencia();
        frmHome.setVisible(true);
    }//GEN-LAST:event_subMantenimientoProcedenciaMousePressed

    private void MantenimentoEquipamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimentoEquipamientoMousePressed
        TipoMantenimiento tipoM = new TipoMantenimiento();
       tipoM.setVisible(true);
    }//GEN-LAST:event_MantenimentoEquipamientoMousePressed

    private void EquipamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipamientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipamientoMouseClicked

    private void EquipamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EquipamientoMousePressed
        // TODO add your handling code here:
          Equipamiento Equi = new Equipamiento();
          Equi.setVisible(true);
        
    }//GEN-LAST:event_EquipamientoMousePressed

    private void EquipamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EquipamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EquipamientoActionPerformed

    private void MantenimientoEquipamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoEquipamientoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimientoEquipamientoMouseClicked

    private void MantenimientoEquipamientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MantenimientoEquipamientoMousePressed
        // TODO add your handling code here:
          MantenimientoEquipamiento Mant= new MantenimientoEquipamiento();
          Mant.setVisible(true);
    }//GEN-LAST:event_MantenimientoEquipamientoMousePressed

    private void MantenimentoEquipamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimentoEquipamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MantenimentoEquipamientoActionPerformed

    private void menuRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistroMousePressed
        // TODO add your handling code here:
        registro reg= new registro();
        reg.setVisible(true);
    }//GEN-LAST:event_menuRegistroMousePressed

    private void MonitoreoCentralMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MonitoreoCentralMousePressed
        // TODO add your handling code here:
        MonitoreoCentral central= new MonitoreoCentral();
        central.setVisible(true);
    }//GEN-LAST:event_MonitoreoCentralMousePressed

    private void SalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMousePressed
        // TODO add your handling code here:
        this.dispose();
        login login = new login();
        login.setVisible(true);
    }//GEN-LAST:event_SalirMousePressed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void historialMantenimientoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialMantenimientoMousePressed
        // TODO add your handling code here:
        HistorialMantenimientos historial = new HistorialMantenimientos();
        historial.setVisible(true);
                
    }//GEN-LAST:event_historialMantenimientoMousePressed

    private void historialMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialMantenimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historialMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Equipamiento;
    private javax.swing.JMenuItem MantenimentoEquipamiento;
    private javax.swing.JMenuItem MantenimientoEquipamiento;
    private javax.swing.JMenu MonitoreoCentral;
    private javax.swing.JMenu Salir;
    private javax.swing.JMenu historialMantenimiento;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JLabel lbInfo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JMenu menuMantenimiento;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenuItem subMantenimientoMarca;
    private javax.swing.JMenuItem subMantenimientoProcedencia;
    // End of variables declaration//GEN-END:variables
}
